spring.application.name=job_tracker
#JPA AND MYSQL
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
server.port=${SERVER_PORT:9852}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#File Upload Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
